#!/bin/sh
# grab and install prads
# comotion@krutt.org

PKG=bup
REPO=git://github.com/bup/$PKG.git

#apt-get install python2.6-dev python-fuse
#apt-get install python-pyxattr python-pylibacl
#apt-get install linux-libc-dev
# or
apt-get build-dep bup

mkdir -p inst
cd inst
if [ ! -d $PKG/.git ]
then
   git clone $REPO
fi

cd $PKG
git pull

make
make test
make install

# bup index -ux /home/zz
# bup save -n laptop /home/zz
# bup save -r mysever -n laptop /home/zz
# bup on myserver index -ux /home/zz
# bup on myserver save -n server /home/zz
# bup ls laptop/latest/home/zz

