#!/bin/sh
# grab and install daemontools-encore
# comotion@krutt.org 2011-05-29

PKG=daemontools-encore
REPO=git://github.com/bruceg/daemontools-encore.git
# used to be available at
#REPO=http://untroubled.org/git/daemontools-encore.git

mkdir -p inst
cd inst
if [ ! -d $PKG/.git ]
then
   git clone $REPO
fi

cd $PKG
git pull
if [ ! -f Makefile ]
   then
   ./makemake
fi
if [ ! -f rts ]
   then
   make
fi

if ! which svscanboot >/dev/null
   then
   make install
fi

if [ ! -d /service ]
   then
   mkdir -p /service
fi
# make sure we don't install twice
if [ ! -f /etc/inittab ]
   then
   if [ -d /etc/init/ ]; then
       # fucking upstart.
       # note Edgy had 'runlevel-2' not 'runlevel 2' nor 'runlevel [2345]'
       # note older distros put this in /etc/event.d/svscanboot
       cat >> /etc/init/svscanboot.conf << EOF
# svscanboot - DJB's daemontools
#
# This service maintains svscanboot from the point the system is
# started until it is shut down again.

start on runlevel [2345]

stop on shutdown

respawn
exec /usr/local/bin/svscanboot

EOF
    elif [ -d /lib/systemd ]; then
        # fucking daemontools
        cat >> /lib/systemd/system/daemontools.service << EOF
[Unit]
Description=DJB daemontools
After=sysinit.target

[Service]
ExecStart=/usr/local/bin/svscanboot
Restart=always

[Install]
WantedBy=multi-user.target
EOF
        chmod a+r /lib/systemd/system/daemontools.service
        ln -s /lib/systemd/system/daemontools.service /etc/systemd/system/multi-user.target.wants/ 
    fi
elif ! grep -q svscanboot /etc/inittab
then
   echo SV:123456:respawn:/usr/local/bin/svscanboot >> /etc/inittab
fi

