#!/bin/sh
#
# install munin and setup plugins
# munin 2.0 from git-svn oh yes
# this is the server setup
#
# TODO: where is munin-graph?
# TODO: munin-async-* crap and 
# on-demand-graphing http://munin-monitoring.org/wiki/CgiHowto
# rrdcached http://sourceforge.net/mailarchive/message.php?msg_name=4BEDB877.9050004%40zvala.cz
# munin-node-awk
# comotion@krutt.org

# req'd
apt-get install git-svn libhtml-template-perl liblog-log4perl-perl
# unfortunate dependency hell - req'd
apt-get install librrds-perl
# optional
apt-get install libnet-ssleay-perl libnet-snmp-perl

mkdir -p inst
cd inst
if [ ! -d munin ]
   then
   git svn clone -rHEAD svn://munin-monitoring.org/munin/trunk munin
fi

cd munin
git svn rebase

if ! getent passwd munin 2>/dev/null >/dev/null
   then
   echo 'munin:x:115:' >> /etc/group
   echo 'munin:x:110:115::/var/lib/munin:/bin/false' >> /etc/passwd
fi

if [ ! -f munin.patched ]
   then
   patch -p1 << EOF
diff --git a/Makefile.config b/Makefile.config
index 8f2a4f1..ad7b340 100644
--- a/Makefile.config
+++ b/Makefile.config
@@ -17,10 +17,10 @@
 #
 # the base of the Munin installation.
 # 
-PREFIX     = $(DESTDIR)/opt/munin
+PREFIX     = $(DESTDIR)/usr/local
 
 # Where Munin keeps its configurations (server.conf, client.conf, ++)
-CONFDIR    = $(DESTDIR)/etc/opt/munin
+CONFDIR    = $(DESTDIR)/etc/munin
 
 # Server only - where to put munin-cron
 BINDIR     = $(PREFIX)/bin
@@ -35,24 +35,24 @@ DOCDIR     = $(PREFIX)/doc
 MANDIR     = $(PREFIX)/man
 
 # Where to put internal binaries and plugin repository
-LIBDIR     = $(PREFIX)/lib
+LIBDIR     = $(PREFIX)/munin
 
 # Server only - Output directory
-HTMLDIR    = $(PREFIX)/www
-CGIDIR     = $(PREFIX)/www/cgi
+HTMLDIR    = $(DESTDIR)/var/www/munin/docs
+CGIDIR     = $(DESTDIR)/var/www/munin/cgi
 
 # Server only - spool directory for data gathered from nodes by
 # munin-gather - experimental.  Place on ramdisk to make munin
 # scale better.  On many versions of Linux as well as on Solaris
 # /tmp will be a ramdisk.
 
-SSPOOLDIR  = $(PREFIX)/spool
+SSPOOLDIR  = $(DESTDIR)/var/munin/sspool
 
 # Suggested directory name for a pulic ramdisk based tmp directory.
 # SSPOOLDIR := /tmp/muninspool
 
 # Where to put RRD files and other internal data, both master and node
-DBDIR      = $(DESTDIR)/var/opt/munin
+DBDIR      = $(DESTDIR)/var/munin
 
 # Client only - Where the spool files are written. Must be writable by
 # group "munin", and should be preserved between reboots
@@ -63,7 +63,7 @@ SPOOLDIR   = $(DBDIR)/spool
 PLUGSTATE  = $(DBDIR)/plugin-state
 
 # Where Munin should place its logs.
-LOGDIR     = $(PREFIX)/log/munin
+LOGDIR     = $(DESTDIR)/var/log/munin
 
 # Location of PID files and other statefiles. On the server, must be
 # writable by the user "munin".
@@ -99,7 +99,7 @@ JAVALIBDIR:= $(LIBDIR)
 GOODSH     := $(shell PATH=`getconf PATH 2>/dev/null || echo $(PATH)` sh -c 'type sh | sed "s/.* //"')
 
 # Path of bash for bash specific plugins
-BASH       := /bin/bash
+BASH       := /bin/sh
 
 # Server only - Where to install the perl libraries
 PERLSITELIB := $(shell $(PERL) -V:sitelib | cut -d"'" -f2)
EOF
   date >> munin.patched
fi

if [ -z "`which munin-node`" ]
then
   make
   make install
fi

if [ ! -f /etc/cron.d/munin ]
   then
   cat resources/linux-cron.d_munin.in | sed 's|@@BINDIR@@|/usr/local/bin|g' >> /etc/cron.d/munin
fi

chgrp -R munin /usr/local/munin/
chgrp -R munin /etc/munin
chmod a+X -R /usr/local/munin
chmod a+X -R /usr/local/share

# enable some nodes
munin-node-configure --shell --families=contrib,auto  | sh -x
chown munin:munin /var/log/munin/
chmod g+s /var/log/munin

