#!/bin/sh -x
#
#
# www.ossec.net
# unfortunately lacks debian packaging.
# get it up and running as a controlling thing
# 
# idempotent script!

# server, agent, local
USER_INSTALL_TYPE=${1:-agent}
#USER_AGENT_SERVER_IP=
#USER_EMAIL_ADDRESS=
USER_EMAIL_SMTP=localhost

USER_DIR=/var/ossec
USER_LANGUAGE=en
#USER_BINARYINSTALL=yes
USER_ENABLE_EMAIL=yes
USER_ENABLE_SYSLOG=yes
USER_ENABLE_SYSCHECK=yes
USER_ENABLE_ROOTCHECK=yes
USER_ENABLE_ACTIVE_RESPONSE=yes
USER_NO_STOP=yes
USER_UPDATE_RULES=yes

apt-get install build-essential

SOURCE=http://www.ossec.net/files
PKG=ossec-hids-latest
mkdir -p inst
cd inst
wget $SOURCE/${PKG}_sum.txt -qO - | grep 'SHA1.*gz' | sed 's/hids.*tar.gz/hids-latest.tar.gz/' > ossec-hids-latest_sum.txt
if [ -f ossec-hids-sum.txt ] && diff -q ossec-hids-sum.txt ossec-hids-latest_sum.txt
then
   echo ossec already installed
   exit 0
else
   cp ossec-hids-latest_sum.txt ossec-hids-sum.txt
fi

wget -c $SOURCE/${PKG}.tar.gz
sha1sum -c ossec-hids-sum.txt || exit 0

tar xvf ossec-hids-latest.tar.gz
cd ossec-hids-*
./install.sh


