#!/bin/sh
# make sure what goes where
#
# try hard to only overwrite silly defaults
# comotion@krutt.org

for user in root kwy comotion
do
  if getent passwd $user >/dev/null
     then
     dir=`getent passwd $user | cut -f 6 -d :`
     chattr +a $dir/.bash_history
  fi
done

BLACKFILE=/etc/modprobe.d/blacklist.conf
BLACKLIST='rds econet'
for module in $BLACKLIST
do
    if ! grep -q "blacklist $module" $BLACKFILE
        then
        echo "blacklist $module" >> $BLACKFILE
    fi
done

if [ -f /etc/default/grub ] && ! grep -q supports_quiet /etc/default/grub
    then
    echo 'supports_quiet=false' >> /etc/default/grub
    update-grub
fi

c=/etc/ssh/ssh_config
if [ -f $c ]
    then
    for key in VisualHostKey VerifyHostKeyDNS
    do
        if ! grep -q "^ *$key" $c
            then
            echo "$key yes" >> $c
        fi
    done
    if ! grep -q '^ *Ciphers' $c
        then
        echo 'Ciphers aes256-ctr,aes192-ctr,aes128-ctr,arcfour256,aes128-cbc' >> $c
    fi
    if ! grep -q '^ *MACs' $c
        then
        echo 'MACs hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-ripemd160' >> $c
    fi
fi



