#!/bin/sh
# make sure what goes where
#
# comotion@krutt.org

for user in root kwy comotion
do
  if getent passwd $user >/dev/null
     then
     dir=`getent passwd $user | cut -f 6 -d :`
     chattr +a $dir/.bash_history
  fi
done

BLACKFILE=/etc/modprobe.d/blacklist.conf
BLACKLIST='rds econet'
for module in $BLACKLIST
do
    if ! grep -q "blacklist $module" $BLACKFILE
        then
        echo "blacklist $module" >> $BLACKFILE
    fi
done

if [ -f /etc/default/grub ] && ! grep -q supports_quiet /etc/default/grub
    then
    echo 'supports_quiet=false' >> /etc/default/grub
    update-grub
fi
