#!/bin/sh
# make sure what goes where
#
# try hard to only overwrite silly defaults
# comotion@krutt.org

apt-get install john chkrootkit rkhunter
for user in root kwy comotion
do
  if getent passwd $user >/dev/null
     then
     dir=`getent passwd $user | cut -f 6 -d :`
     chattr +a $dir/.bash_history
  fi
done

BLACKFILE=/etc/modprobe.d/blacklist.conf
BLACKLIST='rds econet'
for module in $BLACKLIST
do
    if ! grep -q "blacklist $module" $BLACKFILE
        then
        echo "blacklist $module" >> $BLACKFILE
    fi
done

if [ -f /etc/default/grub ] && ! grep -q supports_quiet /etc/default/grub
    then
    echo 'supports_quiet=false' >> /etc/default/grub
    update-grub
fi

c=/etc/ssh/ssh_config
if [ -f $c ]
    then
    for key in VisualHostKey VerifyHostKeyDNS
    do
        if ! grep -q "^ *$key" $c
            then
            echo "$key yes" >> $c
        fi
    done
    if ! grep -q '^ *Ciphers' $c
        then
        # disable gcmrekey.adv and prefer stronger crypto
        echo 'Ciphers aes256-ctr,aes192-ctr,aes128-ctr,blowfish-cbc,arcfour256,aes192-cbc,aes128-cbc' >> $c
    fi
    if ! grep -q '^ *MACs' $c
        then
        echo 'MACs hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-ripemd160' >> $c
    fi
fi

# sshd: disable dsa and ecdsa, and use strong ciphers
sed -i 's/^HostKey .*dsa/#&/' /etc/ssh/sshd_config
if ! grep -q '^ *Ciphers ' /etc/ssh/sshd_config
   then
   sed -i '/^HostKey .*/a \
Ciphers aes256-ctr,aes128-ctr
MACs hmac-sha2-512,hmac-sha2-256,hmac-ripemd160
KexAlgorithms diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1' /etc/ssh/sshd_config
fi



