#!/bin/sh
#
# Check if the harddrive is failing

apt-get install smartmontools

sed -i 's/^#start_smart/start_smart/' /etc/default/smartmontools
/etc/init.d/smartmontools restart

# check what's up
for disk in `cat /proc/partitions | awk '/[sh]d.$/ { print $4 }'`
   do
   smartctl --attributes --log=selftest --quietmode=errorsonly $disk
done


