#!/bin/sh
# grab and install ucspi tools
# comotion@krutt.org 2011-05-29

PKG=ucspi-tcp
REPO=https://github.com/comotion/$PKG.git

mkdir -p inst
cd inst
if [ ! -d $PKG/.git ]
then
   git clone $REPO
fi

cd $PKG
git pull
make && make setup check

