#!/bin/sh
# yes the shell
# 2010-08-31 Kacper Wysocki <comotion@krutt.org> Initial version
# 
# bottom up is better than top down
#
# run the defaults as well as host specific code

host=`hostname -f`
# if you want different module-specific defaults for $host, pass spec here
case $host in
	kwy.u*)
          spec=server
          ;;
        *)
          spec=
esac

doscript() {
   script=$1
   shift
   echo "execing $script"
   modules/$script $@
}

do_plural() {
   for script in $@
   do
      doscript $script $spec
   done
}

echo "the default is never good enough"
do_plural git policy ubuntu lowpower dote_firewall prads

echo "host specific defaults for $host"
case $host in
     bt*)
      # not ossec
      ;;
     *)
      do_plural ossec
esac

echo "TODO gone:"
echo "lua openframework irc"
echo " first: munin nagios " # oh really?
echo "multilog girocco"
echo " then: logwatch rkhunter rootmail firewall"
echo " esoteric: kexec prads and cronpull"
echo " crucial: mail web php cache proxy dns"
echo " optional: integrate with slaughter, chef, puppet"
echo "distributed shell nodes"
echo " advanced: grsecurity, chrooted services, snort, prey"
