#!/bin/sh
# yes the shell
# 2010-08-31 Kacper Wysocki <comotion@krutt.org> Initial version
# 
# bottom up is better than top down
#
# run the defaults as well as host specific code

doscript() {
   script=$1
   shift
   echo "execing $script"
   modules/$script $@
}

case `hostname -f` in
	kwy.u*)
          spec=server
          ;;
        *)
          spec=
esac

echo "the default is never good enough"

doscript lowpower
doscript ubuntu
doscript dote_firewall $spec
doscript ossec $spec

echo " first: ossim munin nagios"
echo "multilog gitorius gitolite"
echo " then: logwatch rkhunter rootmail firewall"
echo " esoteric: kexec lowpower prads and cronpull"
echo " crucial: mail web php cache proxy dns"
echo " optional: integrate with slaughter, chef, puppet"
echo "distributed shell nodes"
echo " advanced: grsecurity, chrooted services, snort"
