#!/bin/sh
# yes the shell
# 2010-08-31 Kacper Wysocki <comotion@krutt.org> Initial version
# 
# bottom up is better than top down
#
# run the defaults as well as host specific code

host=`hostname -f`
case $host in
	kwy.u*)
          spec=server
          ;;
        *)
          spec=
esac

doscript() {
   script=$1
   shift
   echo "execing $script"
   modules/$script $@
}

do_plural() {
   for script in $@
   do
      doscript $script $spec
   done
}

echo "the default is never good enough"
do_plural policy ubuntu lowpower dote_firewall

echo "host specific defaults for $host"
case $host in
   bt*)
      do_plural prads
      ;;
     *)
      do_plural ossec
esac

echo " first: munin nagios "
echo "multilog gitorius gitolite"
echo " then: logwatch rkhunter rootmail firewall"
echo " esoteric: kexec prads and cronpull"
echo " crucial: mail web php cache proxy dns"
echo " optional: integrate with slaughter, chef, puppet"
echo "distributed shell nodes"
echo " advanced: grsecurity, chrooted services, snort, prey"
