#!/bin/sh

verbosity=${verbosity:-0}

doscript() {
   script=$1
   shift
   log 3 "Execing $script"
   if [ -d $script ]; then
      [ -e $script/init ] && $script/init $@
   elif [ -e $script ]; then
      $script $@
   fi;
}

foreach() {
   cmd=$1
   shift;
   for call in $@
   do
      $cmd $call
   done
}

# execute module script and place files where they should be
dosync()  {
   doscript $1
   match_copy $1 "$methods"
}

sync_modules() {
   for module in $MODULES; do
      dosync modules/$module
   done
}

sync_default() {
   match_copy . $methods
}

# Levels:
# 0: fatal
# 1: error
# 2: warn
# 3: info
# 4: debug
log() {
   level=$1
   shift
   if [ $verbosity  -ge $level ] || [ "yes" = "$DEBUG" ]; then
      case "$level" in
         0) echo -n "[fatal] " ;;
         1) echo -n "  [err] " ;;
         2) echo -n " [info] " ;;
         3) echo -n "  [msg] " ;;
         4) echo -n "  [dbg] " ;;
      esac

      echo $@
   fi
}


hd() {
	echo $1
}
