#!/bin/sh

# Example configuration on how to apply default, module specific and
# host specific configuration
#
# Variable overrides:
# $GPG_KEYS    : list of trusted GPG keys
# $MODULES     : List of default modules to apply
# $SYNC_AGENTS : List of functions to call (sequentially) to generate a full config
# $methods     : List of checksum methods that can be called

GPG_KEYS="107B264D CE49888C 845B49F2"
MODULES=""
SYNC_AGENTS="sync_default sync_modules sync_host"

#
# Syncs a files/modules specific for a host. It tries to lookup the
# fqdn (with fallback to hostname) in host/<target>. If found it will
# sync the files and if any modules are found in host/<target>/modules
# these modules will be installed.
sync_host() {
   hosttarget=$([ -d host ] && find host -name $fqdn -or -name $host | head -1)
   if [ ! -z "$hosttarget" ]; then
      dosync $hosttarget

      if [ -f $hosttarget/modules ]; then
         _OLD_MODULES=$MODULES
         MODULES=$(cat $hosttarget/modules)
         log 3 "syncing modules for host $fqdn: $MODULES"
         sync_modules
         MODULES=$_OLD_MODULES
      fi
   else
      log 2 "host $fqdn have no config"
   fi
}
