#!/bin/sh

#
# install varnish + security.vcl
# comotion@krutt.org

apt-get install varnish

# grab security.vcl
mkdir -p inst
cd inst
if [ ! -d security.vcl ]
   then
   git clone git://github.com/comotion/security.vcl.git
fi

cd security.vcl
git pull
cd vcl
make
cd ..

ln -sf $PWD/vcl /etc/varnish/security
