#!/bin/sh

# Backup everything, and optionally log it to somewhere (irc?)
## comotion 2012-02-16
## modified on 2014-01-04 for better backup sets

# set -x
TARGETS="/home /var/mail /opt /etc"
REMOTE=backup:bup

h=$(hostname)
d=/tmp/bup
mkdir -p $d
t=$(tempfile -d "$d")
e=/var/local/backup_expect
x=$d/exclude_fifo
backupset=''

logit()
{
   ii=/usr/local/bin/logit
   if [ -x $ii ]
   then
      $ii "$@"
   else
      echo "$@" >&2
   fi
}

for target in $TARGETS
do
   [ ! -d "$target" ] && continue
   find "$target" -type p -or -type s -or -type b -or -type c > $x
   backupset="$backupset $target"
done

bup index -x --exclude-from "$x" $backupset >/dev/null 2>&1 | egrep -v '^Indexing:|^bup: merging indexes'
bup save -9q -r $REMOTE -n "$h" $backupset >/dev/null 2>&1 | awk ' BEGIN { skipped=0 }
/^WARNING: [0-9]+ errors encountered while saving/ {
   errors=$2
   if (errors != skipped){
      print "HELP, non-trivial errors backing up."
   }
   skipped=0
}
/^\[Errno 2\] No such file or directory: ..etc.dnscache.log.main/ {
   skipped++;
}
/^skipping special file/ {
   skipped++;
}
/^Warning: Permanently added/ {
   line++;
}

!/^(skipping|WARNING:| |Traceback) /
{ line++;  }
' > "$t"
# output is empty if everything is ok.
rc=0
if ! test -s "$t"
then
   logit "I am all backed up."
   rm "$t"
elif test -r "$e" && diff -u "$t" "$e"
   then
   logit "Today is the same shit as yesterday. (someone check $e)"
   rm "$t"
   rc=2
else
   logit "Bup pooped it, check $t for the details."
   # make this test silent if the same problem repeats
   cp "$t" "$e"
   rc=1
fi

exit $rc

