#!/bin/sh
#
# Re-apply gone configuration
# comotion@krutt.org 2010

gonedir=${1:-/root/gone}

cd $gonedir
tf=`tempfile || exit 1`
git log -1 > $tf
git pull >/dev/null 2>/dev/null
# don't apply if no change
if git log -1 | diff $tf -
then
   : #no change
else
   USER_CHOSE=a ./apply >/dev/null
fi
rm -f $tf

