#!/bin/sh
### BEGIN INIT INFO
# Provides:          ossec
# Required-Start:    $syslog snort
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: OSSEC system daemons
# Description:       Starts and stops the OSSEC daemons
#                    
### END INIT INFO

# OSSEC	        Controls OSSEC HIDS
# Author:       Daniel B. Cid <dcid@ossec.net>
# Modified for slackware by Jack S. Lai
# Modified for debian by Kacper Wysocki <comotion@users.sf.net>


. /etc/ossec-init.conf
if [ "X${DIRECTORY}" = "X" ]; then
    DIRECTORY="/var/ossec"
fi

    
start() {
	${DIRECTORY}/bin/ossec-control start
}

stop() {
	${DIRECTORY}/bin/ossec-control stop
}

status() {
	${DIRECTORY}/bin/ossec-control status
}


case "$1" in
  start)
	start
	;;
  stop) 
	stop
	;;
  restart)
	stop
	start
	;;
  status)
    status
	;;
  *)
	echo "*** Usage: $0 {start|stop|restart|status}"
	exit 1
esac

exit 0
